// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/// <reference types="node" />
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // For Prisma CLI operations (migrations, db push), use DIRECT_URL
    // This should be a standard postgresql:// connection string from your Neon dashboard
    // DATABASE_URL is for Prisma Accelerate (used in PrismaClient constructor at runtime)
    url: process.env["DIRECT_URL"] || (() => {
      if (!process.env["DATABASE_URL"]) {
        throw new Error("Either DIRECT_URL or DATABASE_URL must be set in .env");
      }
      // If DATABASE_URL is a prisma+ URL, it cannot be used for CLI operations
      if (process.env["DATABASE_URL"].startsWith("prisma+")) {
        throw new Error(
          "DATABASE_URL uses Prisma Accelerate format. " +
          "Please set DIRECT_URL in .env with a direct PostgreSQL connection string " +
          "from your Neon dashboard (format: postgresql://user:password@host:port/dbname)"
        );
      }
      return process.env["DATABASE_URL"];
    })(),
  },
});
