import { KVKDetails } from '../types/kvk'
import { BankAccount } from '../types/bankAccount'
import { Staff } from '../types/staff'
import { localStorageService } from './localStorageService'
import { mockVehicleDetails, mockEquipmentDetails, mockInfrastructureList } from '../mocks/kvkMockData'

// Mock KVK Data
export const mockKVKData: KVKDetails[] = [
    {
        id: 13,
        state_id: 1,
        uni_id: 1,
        district_id: 1,
        kvk_name: 'KVK Patna',
        mobile: '9876543210',
        email: 'kvk.patna@atari.gov.in',
        fax: '0612-1234567',
        landline: '0612-1234567',
        address: 'Patna, Bihar',
        org_name: 'Bihar Agricultural University',
        org_mobile: '9876543211',
        org_landline: '0612-1234568',
        org_fax: '0612-1234568',
        org_email: 'bau@bihar.gov.in',
        org_address: 'Sabour, Bhagalpur, Bihar',
        sanction_year: '2000',
        total_land: '50 hectares',
        deleted_at: null,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        district: {
            id: 1,
            st_id: '1',
            uni_id: 1,
            district_name: 'Patna',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        },
        university: {
            id: 1,
            state_id: 1,
            university_name: 'Bihar Agricultural University',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        },
        state: {
            id: 1,
            zone_id: 1,
            state_name: 'Bihar',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            zone: {
                id: 1,
                zone_name: 'Zone 1',
                created_at: new Date().toISOString(),
                updated_at: new Date().toISOString(),
            },
        },
    },
    {
        id: 14,
        state_id: 1,
        uni_id: 1,
        district_id: 2,
        kvk_name: 'KVK Araria',
        mobile: '9876543212',
        email: 'kvk.araria@atari.gov.in',
        fax: '0612-1234569',
        landline: '0612-1234569',
        address: 'Araria, Bihar',
        org_name: 'Bihar Agricultural University',
        org_mobile: '9876543213',
        org_landline: '0612-1234570',
        org_fax: '0612-1234570',
        org_email: 'bau@bihar.gov.in',
        org_address: 'Sabour, Bhagalpur, Bihar',
        sanction_year: '2001',
        total_land: '45 hectares',
        deleted_at: null,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        district: {
            id: 2,
            st_id: '1',
            uni_id: 1,
            district_name: 'Araria',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        },
        university: {
            id: 1,
            state_id: 1,
            university_name: 'Bihar Agricultural University',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        },
        state: {
            id: 1,
            zone_id: 1,
            state_name: 'Bihar',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            zone: {
                id: 1,
                zone_name: 'Zone 1',
                created_at: new Date().toISOString(),
                updated_at: new Date().toISOString(),
            },
        },
    },
]

// Mock Bank Account Data
export const mockBankAccounts: BankAccount[] = [
    {
        id: 1,
        kvk_id: 13,
        user_id: 3,
        account_type: 'Kvk',
        account_name: 'KVK Patna Account',
        bank_name: 'State Bank of India',
        location: 'Patna',
        account_number: '1234567890',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
    {
        id: 2,
        kvk_id: 13,
        user_id: 3,
        account_type: 'Revolving Fund',
        account_name: 'KVK Patna Revolving Fund',
        bank_name: 'State Bank of India',
        location: 'Patna',
        account_number: '1234567891',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
    {
        id: 3,
        kvk_id: 14,
        user_id: 4,
        account_type: 'Kvk',
        account_name: 'KVK Araria Account',
        bank_name: 'Punjab National Bank',
        location: 'Araria',
        account_number: '9876543210',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
]

// Mock Staff Data
export const mockStaff: Staff[] = [
    {
        id: 1,
        kvk_id: 13,
        staff_name: 'Dr. Rajesh Kumar',
        post_id: 1,
        position: 1,
        mobile: '9876543201',
        email: 'rajesh.kumar@kvkpatna.gov.in',
        designation: 'Program Coordinator',
        discipline: 'Agronomy',
        pay_scale: 'Level 10',
        date_of_joining: '2010-01-15',
        releaving_date: null,
        pay_band: 'PB-3',
        dob: '1980-05-20',
        job_type: 'Regular',
        alliances: 'None',
        specialization: 'Crop Production',
        cast_category: 'General',
        photo: undefined,
        resume: undefined,
        is_transferred: 0,
        deleted_at: null,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        post: {
            id: 1,
            post_name: 'Program Coordinator',
            chart_label: 'PC',
            deleted_at: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        },
    },
    {
        id: 2,
        kvk_id: 13,
        staff_name: 'Dr. Priya Sharma',
        post_id: 2,
        position: 2,
        mobile: '9876543202',
        email: 'priya.sharma@kvkpatna.gov.in',
        designation: 'Subject Matter Specialist',
        discipline: 'Plant Protection',
        pay_scale: 'Level 9',
        date_of_joining: '2012-03-10',
        releaving_date: null,
        pay_band: 'PB-3',
        dob: '1985-08-15',
        job_type: 'Regular',
        alliances: 'None',
        specialization: 'Integrated Pest Management',
        cast_category: 'OBC',
        photo: undefined,
        resume: undefined,
        is_transferred: 0,
        deleted_at: null,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        post: {
            id: 2,
            post_name: 'Subject Matter Specialist',
            chart_label: 'SMS',
            deleted_at: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        },
    },
    {
        id: 3,
        kvk_id: 14,
        staff_name: 'Dr. Amit Singh',
        post_id: 1,
        position: 1,
        mobile: '9876543203',
        email: 'amit.singh@kvkararia.gov.in',
        designation: 'Program Coordinator',
        discipline: 'Horticulture',
        pay_scale: 'Level 10',
        date_of_joining: '2011-06-20',
        releaving_date: null,
        pay_band: 'PB-3',
        dob: '1982-11-30',
        job_type: 'Regular',
        alliances: 'None',
        specialization: 'Fruit Production',
        cast_category: 'General',
        photo: undefined,
        resume: undefined,
        is_transferred: 0,
        deleted_at: null,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        post: {
            id: 1,
            post_name: 'Program Coordinator',
            chart_label: 'PC',
            deleted_at: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        },
    },
]

// Initialize mock data
export const initializeMockData = () => {
    localStorageService.initializeMockData(mockKVKData, mockBankAccounts, mockStaff)
    // Seed About KVK new modules on first run (if keys not present)
    localStorageService.initializeAboutKvkMockData(
        mockVehicleDetails as any,
        mockEquipmentDetails as any,
        mockInfrastructureList as any
    )

    // Set up KVK user mapping
    const mapping: Record<string, number> = {
        '3': 13, // KVK user ID 3 maps to KVK ID 13 (Patna)
        '4': 14, // KVK user ID 4 maps to KVK ID 14 (Araria)
    }
    localStorage.setItem('atari-kvk-user-mapping', JSON.stringify(mapping))
}
